#!/bin/bash
# optionally take a plan.properties file as the cmd line argument; quit if it errs to avoid the long display of diff cmd output

# default pf test/plan.properties
if [ $# -lt 1 ] ; then
  pf=test/plan.properties
else
  pf=$1
fi

# run and catch the error if there is any
el=error.log
ruby lifecastor.rb -v  $pf > test/zz.f 2>  $el
ruby lifecastor.rb -tv $pf > test/zz.t 2>> $el

# if erred, show errors then quit; ow diff the results
if [[ -s $el ]]; then
  cat $el
  exit
else
  diff test/archive.f test/zz.f
  diff test/archive.t test/zz.t
fi;
